#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s
#  2. INTEGER t
#  3. INTEGER a
#  4. INTEGER b
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#

def countApplesAndOranges(s, t, a, b, apples, oranges):
    # Write your code here
    numApples = 0 #Assign 0 to numApples
    numOranges = 0 #Assign 0 to numOranges
    
    for i in apples: #Iterate through apples list
        applePosition = a + i #Add a to apples element and assign result to applePosition
        
        if applePosition >= s and applePosition <= t: #If applePosition is greater than or equal to s and less than or equal to t
        
            numApples += 1 #Increment 1 to numApples
            
    for i in oranges: #Iterate through oranges list
        orangePosition = b + i #Add b to oranges element and assign result to orangePosition
        
        if orangePosition >= s and orangePosition <= t: #If orangePosition is greater than or equal to s and less than or equal to t
        
            numOranges += 1 #Increment 1 to numOranges
            
            
    print(numApples) #Print numApples
    print(numOranges) #Print numOranges
                    
    
    

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    s = int(first_multiple_input[0])

    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    a = int(second_multiple_input[0])

    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    m = int(third_multiple_input[0])

    n = int(third_multiple_input[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
