#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'compareTriplets' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def compareTriplets(a, b):
    # Write your code here
    a_score = 0 #Assign 0 to a_score
    b_score = 0 #Assign 0 to b_score
    
    for i in range(0,3): #Iterate 3 times
        if a[i] > b[i]: #If a element at index i is greater than b element at index i
            a_score += 1 #Increment 1 to a_score

        elif a[i] < b[i]: #If a element at index i is less than b element at index i
            b_score += 1 #Increment 1 to b_score

    return [a_score, b_score]  #Return a_score and b_score

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
