#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'dayOfProgrammer' function below.
#
# The function is expected to return a STRING.
# The function accepts INTEGER year as parameter.
#

def dayOfProgrammer(year):
    # Write your code here
    
    if year == 1918: #If year is equal to 1918
        return "26.09.1918" #Return "26.09.1918"
    
    elif year % 4 == 0 and year < 1918: #If year is divisible by 4 and less than 1918
        numDays = 31 + 29 + 31 + 30 + 31 + 30 + 31 + 31 #Find the numDays for a leap year
        
        dd = 256 - numDays #Subtract numDays from 256
        
        return str(dd) + ".09." + str(year) #Return date
        
    elif year % 4 != 0 and year < 1918: #If year is not divisible by 4 and less than 1918
        numDays = 31 + 28 + 31 + 30 + 31 + 30 + 31 + 31 #Find the numDays for a non leap year
        
        dd = 256 - numDays #Subtract numDays from 256
        
        return str(dd)+ ".09." + str(year) #Return date
        
    elif (year % 400 == 0 or (year % 4 == 0 and year % 100 != 0)) and (year >= 1700 and year <= 2700): #If year is divisible by 400 or divisible by 4 and not divisible by 100, and is in the inclusive range 1700 to 2700
        numDays = 31 + 29 + 31 + 30 + 31 + 30 + 31 + 31 #Find the numDays for a leap year
        
        dd = 256 - numDays #Subtract numDays from 256
        
        return str(dd) + ".09." + str(year) #Return date
        
    else: #Else statement
        
        numDays = 31 + 28 + 31 + 30 + 31 + 30 + 31 + 31 #Find the numDays for a non leap year
        
        dd = 256 - numDays #Subtract numDays from 256
        
        return str(dd)+ ".09." + str(year) #Return date
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(input().strip())

    result = dayOfProgrammer(year)

    fptr.write(result + '\n')

    fptr.close()
