#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pageCount' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER p
#

def pageCount(n, p):
    # Write your code here
    
    pages = []
    
    beginToEnd = 0
    
    endToBegin = 0
    
    for i in range(1, (n+1)):
        pages.append(i)
    
    for i in range(0, len(pages)):
        if pages[i] == p:
            break
        else:
            beginToEnd += 1
            
    for i in range((len(pages) - 1), -1, -1):
        if pages[i] == p:
            break
        else:
            endToBegin += 1
            
    if (beginToEnd / 2) < (endToBegin / 2) and beginToEnd != 1:
        return int(beginToEnd / 2)
        
    elif (beginToEnd / 2) < (endToBegin / 2) and beginToEnd == 1:
        return beginToEnd
        
    elif (beginToEnd / 2) > (endToBegin / 2):
        return int(endToBegin / 2)
            
    

    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    p = int(input().strip())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
