#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'extraLongFactorials' function below.
#
# The function accepts INTEGER n as parameter.
#

def extraLongFactorials(n):
    # Write your code here
    factorial = 1 #Assign 1 to factorial
    
    for i in range(n, 0 , -1): #Iterate n times
        factorial *= i #Mulitply i to factorial
        
    print(factorial) #Print factorial

if __name__ == '__main__':
    n = int(input().strip())

    extraLongFactorials(n)
