#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
    # Write your code here
    
    finalGrades = [] #Create empty list
    
    for element in grades: #Iterate through grades list
        
        if element < 35: #If element is less than 35
            finalGrades.append(element) #Append element to finalGrades list
            continue #Move to next element
        
        initialGrade = element #Assign element to initialGrade
        
        while element % 5 != 0: #While element is not divisible by 5
            element += 1 #Increment 1 to element
            
        if (element - initialGrade) < 3: #If element - initialGrade is less than 3
            finalGrades.append(element) #Append element to finalGrades
            
        else: #Else statement
            finalGrades.append(initialGrade) #Append initialGrade to finalGrades
            
    return finalGrades #Return finalGrades

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
